### ISSUE TITLE
PENDING FOR OVER 48 HOURS

### ISSUE THREAD

**Issue by ghost** [hivewallet/hive-mac#481]
So my understanding is that on you cannot transfer any funds if you have a transaction pending, that would be fine and all but for some reason my transfer has been pending with 0 confirmations  with the status " not broadcasted yet" and obviously nothing showing on blockchain… Has anyone been experiencing any problems with hive, was hoping someone here knew something juicy!

**Comment by mackuba** [comment]
Hi,

Hive has been officially unmaintained since last winter. It's working for now, but I don't know for how much longer (macOS 10.12 was supposed to drop support for old Java which Hive uses, but it looks like they've kept it for now).

As for problems with transactions, check out the [FAQ](https://github.com/hivewallet/hive-mac/wiki/FAQ#common-problems-and-known-issues), especially [this entry](https://github.com/hivewallet/hive-mac/wiki/FAQ#ive-sent-a-transaction-but-its-stuck-as-pending-and-doesnt-get-confirmed).
